// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Choice struct {
	ID         string    `json:"id"`
	Question   *Question `json:"question"`
	QuestionID string    `json:"question_id"`
	ChoiceText string    `json:"choice_text"`
}

type ChoiceInput struct {
	QuestionID string `json:"question_id"`
	ChoiceText string `json:"choice_text"`
}

type Question struct {
	ID           string    `json:"id"`
	QuestionText string    `json:"question_text"`
	PubDate      string    `json:"pub_date"`
	Choices      []*Choice `json:"choices"`
}

type QuestionInput struct {
	QuestionText string `json:"question_text"`
	PubDate      string `json:"pub_date"`
}
